### ISSUE TITLE
key error?

### ISSUE THREAD

**Issue by xuhuaq** [mhwgoo/cambridge#1]
C:\Users\abc>camb commit
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\camb.exe\__main__.py", line 4, in <module>
  File "c:\python39\lib\site-packages\cambridge\cambridge.py", line 512, in <module>
    from .log import logger
  File "c:\python39\lib\site-packages\cambridge\log.py", line 11, in <module>
    data = Path(os.environ["HOME"]).absolute() / ".local" / "share" / "cambridge"
  File "c:\python39\lib\os.py", line 679, in __getitem__
    **raise KeyError(key) from None
KeyError: 'HOME'**

**Comment by mhwgoo** [comment]
Hi xuhuaq, I have solved platform dependent bug leading to failure when getting the home folder on windows os. And the updated package can be fetched by pip now. Thank you for your feedback.
