### ISSUE TITLE
Cannot import fake user agent

### ISSUE THREAD

**Issue by raffaelemancuso** [mhwgoo/cambridge#2]
```
[XXX@XXX Downloads]$ camb hello
Traceback (most recent call last):
  File "/home/XXX/.local/bin/camb", line 5, in <module>
    from cambridge.main import main
  File "/home/XXX/.local/lib/python3.10/site-packages/cambridge/main.py", line 16, in <module>
    from .args import parse_args
  File "/home/XXX/.local/lib/python3.10/site-packages/cambridge/args.py", line 15, in <module>
    from .dicts import webster, cambridge
  File "/home/XXX/.local/lib/python3.10/site-packages/cambridge/dicts/webster.py", line 12, in <module>
    from ..dicts import dict
  File "/home/XXX/.local/lib/python3.10/site-packages/cambridge/dicts/dict.py", line 6, in <module>
    from fake_user_agent import user_agent
ImportError: cannot import name 'user_agent' from 'fake_user_agent' (/home/XXX/.local/lib/python3.10/site-packages/fake_user_agent/__init__.py)
```

**Comment by raffaelemancuso** [comment]
Works after upgrading fake_user_agent
